spring.application.name=RestSpringBootHaxagonal

spring.datasource.url=${DB_URL1}
spring.datasource.username=${DB_USER1}
spring.datasource.password=${DB_PASSWORD1}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=disable

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.org.hibernate.orm.connections=WARN
logging.level.org.hibernate.orm=WARN

logging.level.org.flywaydb.core.internal.database=WARN
logging.level.org.flywaydb.core.internal.jdbc=WARN

app.jwt.secret=chave_com_minimo_32_caracteres_aqui
app.jwt.expiracao-horas=1



